/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cssweb_psamdemo_jni_psamwrapper */

#ifndef _Included_com_cssweb_psamdemo_jni_psamwrapper
#define _Included_com_cssweb_psamdemo_jni_psamwrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cssweb_psamdemo_jni_psamwrapper
 * Method:    open
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cssweb_psamdemo_jni_psamwrapper_open
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
